// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CategorySummary = {
  name: string;
  color: string;
  monthly_amounts: Array<number>;
};
