export const unicornRules = {
	"unicorn/better-regex": "error",
	"unicorn/catch-error-name": "error",
	"unicorn/custom-error-definition": "error",
	"unicorn/no-for-loop": "error",
	"unicorn/no-instanceof-array": "error",
	"unicorn/no-invalid-remove-event-listener": "error",
	"unicorn/no-typeof-undefined": "error",
	"unicorn/no-unnecessary-await": "error",
	"unicorn/no-unused-properties": "error",
	"unicorn/no-useless-spread": "error",
	"unicorn/no-useless-undefined": [
		"error",
		{
			checkArguments: false,
		},
	],
	"unicorn/prefer-add-event-listener": "error",
	"unicorn/prefer-array-index-of": "error",
	"unicorn/prefer-array-some": "error",
	"unicorn/prefer-at": "error",
	"unicorn/prefer-date-now": "error",
	"unicorn/prefer-default-parameters": "error",
	"unicorn/prefer-includes": "error",
	"unicorn/prefer-keyboard-event-key": "error",
	"unicorn/prefer-logical-operator-over-ternary": "error",
	"unicorn/prefer-string-replace-all": "error",
	"unicorn/prefer-string-slice": "error",
	"unicorn/prefer-string-starts-ends-with": "error",
};
